import { chartMassOptions } from "../calc/filtering.js";
import {
  applyDryMassCalculatorPreset,
  armorMaxPoints,
  dryMassCalcArmorTotals,
  dryMassCalcTotalTons,
  exportedDryMassCalculatorPreset,
  hardpointCapacity,
  normalizeDryMassCalcSlots,
  resetDryMassCalcState,
  selectedArmorById,
  selectedShipClass,
  utilityModulesForShipClass,
  weaponModulesForSection,
  weaponSlotSize,
} from "../calc/dry_mass.js";
import { buildAxisTickPlan } from "../chart/axis.js";
import { currentChartRows } from "../chart/context.js";
import { axisSnapshot, render } from "../chart/interaction.js";
import { tooltipRef } from "../chart/rendering.js";
import {
  chartPresetExportObject,
  chartPresetLibrary,
  chartPresetLibraryExportObject,
  dryMassPresetExportObject,
  dryMassPresetLibrary,
  dryMassPresetLibraryExportObject,
  exportedPreset,
  handleImportedPresetObject,
  parsePresetPayload,
  renderDryMassPresetControls,
  renderPresetLibraryControls,
  saveChartPresetFromSettings,
  saveChartPresetLibrary,
  saveDryMassPresetFromCalculator,
  saveDryMassPresetLibrary,
  serializePayloadObject,
  serializePresetPayload,
  setChartPresetLibrary,
  setDryMassPresetLibrary,
  setStartupChartPreset,
  startupChartPresetId,
  applyPresetToState,
} from "../presets/library.js";
import {
  CHART_PRESET_STARTUP_STORAGE_KEY,
  CHART_PRESET_STORAGE_KEY,
  DATA,
  DEFAULT_ARMOR_ID,
  DRY_MASS_PRESET_STORAGE_KEY,
  EMPTY_UTILITY_MODULE,
  EMPTY_WEAPON_MODULE,
  LEFT_PANEL_LAYOUT_STORAGE_KEY,
  SHIP_CLASS_OPTIONS,
  applyLeftPanelOrder,
  dryMassCalcState,
  leftPanelLayout,
  loadLeftPanelLayout,
  resetChartStateToDefaults,
  setLanguage,
  setLeftPanelLayout,
  state,
  updateLeftPanelCardSummaries,
} from "../state/core.js";
import { refreshTooltip } from "../ui/tooltip_table.js";
import { syncUiFromState } from "../presets/library.js";

export function installDebugHooks() {
  const debugApi = {
    get chartPresetLibrary() {
      return chartPresetLibrary;
    },
    set chartPresetLibrary(value) {
      setChartPresetLibrary(value);
    },
    get currentChartRows() {
      return currentChartRows;
    },
    get dryMassPresetLibrary() {
      return dryMassPresetLibrary;
    },
    set dryMassPresetLibrary(value) {
      setDryMassPresetLibrary(value);
    },
    get startupChartPresetId() {
      return startupChartPresetId;
    },
    applyDryMassCalculatorPreset,
    applyLeftPanelOrder,
    applyPresetToState,
    axisSnapshot,
    chartMassOptions,
    chartPresetExportObject,
    chartPresetLibraryExportObject,
    dryMassCalcArmorTotals,
    dryMassCalcState,
    dryMassCalcTotalTons,
    dryMassPresetExportObject,
    dryMassPresetLibraryExportObject,
    exportedDryMassCalculatorPreset,
    exportedPreset,
    handleImportedPresetObject,
    hardpointCapacity,
    loadLeftPanelLayout,
    normalizeDryMassCalcSlots,
    parsePresetPayload,
    refreshTooltip,
    render,
    renderDryMassPresetControls,
    renderPresetLibraryControls,
    resetChartStateToDefaults,
    resetDryMassCalcState,
    saveChartPresetFromSettings,
    saveChartPresetLibrary,
    saveDryMassPresetFromCalculator,
    saveDryMassPresetLibrary,
    selectedArmorById,
    selectedShipClass,
    serializePayloadObject,
    serializePresetPayload,
    setLanguage,
    setLeftPanelLayout,
    setStartupChartPreset,
    state,
    syncUiFromState,
    tickPlan: (min, max, pixelSpan, logScale, options = {}) => buildAxisTickPlan(min, max, pixelSpan, logScale, options),
    tooltipRef,
    updateLeftPanelCardSummaries,
    utilityModulesForShipClass,
    weaponModulesForSection,
    weaponSlotSize,
    CHART_PRESET_STARTUP_STORAGE_KEY,
    CHART_PRESET_STORAGE_KEY,
    DATA,
    DEFAULT_ARMOR_ID,
    DRY_MASS_PRESET_STORAGE_KEY,
    EMPTY_UTILITY_MODULE,
    EMPTY_WEAPON_MODULE,
    LEFT_PANEL_LAYOUT_STORAGE_KEY,
    SHIP_CLASS_OPTIONS,
  };
  window.TI_ENGINE_CHART_DEBUG = debugApi;

  Object.defineProperties(window, {
    applyDryMassCalculatorPreset: { value: applyDryMassCalculatorPreset, configurable: true },
    applyLeftPanelOrder: { value: applyLeftPanelOrder, configurable: true },
    applyPresetToState: { value: applyPresetToState, configurable: true },
    armorMaxPoints: { value: armorMaxPoints, configurable: true },
    chartMassOptions: { value: chartMassOptions, configurable: true },
    chartPresetExportObject: { value: chartPresetExportObject, configurable: true },
    chartPresetLibrary: {
      get: () => chartPresetLibrary,
      set: value => setChartPresetLibrary(value),
      configurable: true,
    },
    chartPresetLibraryExportObject: { value: chartPresetLibraryExportObject, configurable: true },
    currentChartRows: { get: () => currentChartRows, configurable: true },
    dryMassCalcArmorTotals: { value: dryMassCalcArmorTotals, configurable: true },
    dryMassCalcState: { value: dryMassCalcState, configurable: true },
    dryMassCalcTotalTons: { value: dryMassCalcTotalTons, configurable: true },
    dryMassPresetExportObject: { value: dryMassPresetExportObject, configurable: true },
    dryMassPresetLibrary: {
      get: () => dryMassPresetLibrary,
      set: value => setDryMassPresetLibrary(value),
      configurable: true,
    },
    dryMassPresetLibraryExportObject: { value: dryMassPresetLibraryExportObject, configurable: true },
    exportedDryMassCalculatorPreset: { value: exportedDryMassCalculatorPreset, configurable: true },
    exportedPreset: { value: exportedPreset, configurable: true },
    handleImportedPresetObject: { value: handleImportedPresetObject, configurable: true },
    hardpointCapacity: { value: hardpointCapacity, configurable: true },
    leftPanelLayout: {
      get: () => leftPanelLayout,
      set: value => setLeftPanelLayout(value),
      configurable: true,
    },
    loadLeftPanelLayout: { value: loadLeftPanelLayout, configurable: true },
    normalizeDryMassCalcSlots: { value: normalizeDryMassCalcSlots, configurable: true },
    parsePresetPayload: { value: parsePresetPayload, configurable: true },
    refreshTooltip: { value: refreshTooltip, configurable: true },
    render: { value: render, configurable: true },
    renderDryMassPresetControls: { value: renderDryMassPresetControls, configurable: true },
    renderPresetLibraryControls: { value: renderPresetLibraryControls, configurable: true },
    resetChartStateToDefaults: { value: resetChartStateToDefaults, configurable: true },
    resetDryMassCalcState: { value: resetDryMassCalcState, configurable: true },
    saveChartPresetFromSettings: { value: saveChartPresetFromSettings, configurable: true },
    saveChartPresetLibrary: { value: saveChartPresetLibrary, configurable: true },
    saveDryMassPresetFromCalculator: { value: saveDryMassPresetFromCalculator, configurable: true },
    saveDryMassPresetLibrary: { value: saveDryMassPresetLibrary, configurable: true },
    selectedArmorById: { value: selectedArmorById, configurable: true },
    selectedShipClass: { value: selectedShipClass, configurable: true },
    serializePayloadObject: { value: serializePayloadObject, configurable: true },
    serializePresetPayload: { value: serializePresetPayload, configurable: true },
    setLanguage: { value: setLanguage, configurable: true },
    setStartupChartPreset: { value: setStartupChartPreset, configurable: true },
    startupChartPresetId: { get: () => startupChartPresetId, configurable: true },
    state: { value: state, configurable: true },
    syncUiFromState: { value: syncUiFromState, configurable: true },
    tooltipRef: { value: tooltipRef, configurable: true },
    updateLeftPanelCardSummaries: { value: updateLeftPanelCardSummaries, configurable: true },
    utilityModulesForShipClass: { value: utilityModulesForShipClass, configurable: true },
    weaponModulesForSection: { value: weaponModulesForSection, configurable: true },
    weaponSlotSize: { value: weaponSlotSize, configurable: true },
    CHART_PRESET_STARTUP_STORAGE_KEY: { value: CHART_PRESET_STARTUP_STORAGE_KEY, configurable: true },
    CHART_PRESET_STORAGE_KEY: { value: CHART_PRESET_STORAGE_KEY, configurable: true },
    DATA: { value: DATA, configurable: true },
    DEFAULT_ARMOR_ID: { value: DEFAULT_ARMOR_ID, configurable: true },
    DRY_MASS_PRESET_STORAGE_KEY: { value: DRY_MASS_PRESET_STORAGE_KEY, configurable: true },
    EMPTY_UTILITY_MODULE: { value: EMPTY_UTILITY_MODULE, configurable: true },
    EMPTY_WEAPON_MODULE: { value: EMPTY_WEAPON_MODULE, configurable: true },
    LEFT_PANEL_LAYOUT_STORAGE_KEY: { value: LEFT_PANEL_LAYOUT_STORAGE_KEY, configurable: true },
    SHIP_CLASS_OPTIONS: { value: SHIP_CLASS_OPTIONS, configurable: true },
  });
}
